### ISSUE TITLE
1208

### ISSUE THREAD

**Issue by ArchainTsui** [Snapmaker/Snapmaker-English-Writing-Style-Guide#1]
Here are some issues to be confirmed:
***
<b>Abbreviation</b> to <b>Articles</b>
- documentations > documentation?
- Table of Content > Table of Contents?
- distinguish between A, B, C and D > distinguish (among) A, B, C and D?
- Window 10 > Windows 10
- in the following parenthesis > in the following parentheses?
 (unless you are referring to an opening or closing parenthesis)
- provide full form > provide a/its/the full form or full forms? 
(be consistent in the countable or uncountable form of the word FORM)
- if using abbreviation > if using an abbreviation?
- what <b>its</b> refer to > what <b>its</b> refers to?
- difficulty for proofread > difficulty for proofreading?
- consistent with agreement > consistent in agreement?
- explaination > explanation
***

**Comment by The-rambunctious-S** [comment]
All merged  but one: 
"distinguish between A, B, C and D > distinguish (among) A, B, C and D?" 

In this case it's okay to use **distinguish between**.
